### PR TITLE
Add 2 cards to the UI fix

### LINKED ISSUE #370: P-146 Recharge Plug-In Q
UI does not support having 2 under 1 digimon when it dies. Can accidentally select unresolved Recharge and miss out on it's effect. Similar bug with X Antibody Proto Form.

### LINKED ISSUE #412: EX6-042 RaijiLudomon
UI does not support 2 of this card as sources in the same digimon when resolving ESS. No easy determination of which Raiji is using effect to prevent accidentally trashing unused Raiji. - don't test, not touched

### PR DESCRIPTION
**Pull request by x89rt2**

### CODE REVIEW

**Review by hooperk — APPROVED** [review]

File: Assets/Scripts/CardEffect/EX6/Black/EX6_042.cs [hunk 1]
```diff
@@ -373,8 +373,7 @@ IEnumerator ActivateCoroutine(Hashtable hashtable)
                                     canEndNotMax: false,
                                     isShowOpponent: true,
                                     mode: SelectCardEffect.Mode.Custom,
-                                    root: SelectCardEffect.Root.Custom,
-                                    customRootCardList: selectedPermanent.DigivolutionCards,
```
Comment (hooperk) [inline Assets/Scripts/CardEffect/EX6/Black/EX6_042.cs:377]: Don't remove this line

File: Assets/Scripts/CardEffect/P/Yellow/P_146.cs [hunk 2]
```diff
@@ -249,8 +249,7 @@ IEnumerator ActivateCoroutine(Hashtable hashtable)
                         message: "Select 1 card to put in security.",
                         isShowOpponent: true,
                         mode: SelectCardEffect.Mode.Custom,
-                        root: SelectCardEffect.Root.Custom,
-                        customRootCardList: card.PermanentOfThisCard().DigivolutionCards,
```
Comment (hooperk) [inline Assets/Scripts/CardEffect/P/Yellow/P_146.cs:253]: Don't remove this line

**Review by hooperk — CHANGES_REQUESTED** [review]

**Review by hooperk — APPROVED** [review]
